packages:
  - apps/*
  - packages/*
  - '!packages/api/next-config'
  - packages/api/*
  - packages/auth/*
  - packages/content/*
  - packages/features/*
  - packages/integrations/*
  - packages/tooling/*
  - tools/*
overrides:
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  esbuild@<=0.24.2: '>=0.25.0'
  prismjs@<1.30.0: '>=1.30.0'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  estree-util-value-to-estree@<3.3.3: '>=3.3.3'
  vite@>=6.2.0 <6.2.6: '>=6.2.6'
  cookie@<0.7.0: '>=0.7.0'
  '@babel/runtime-corejs3@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  vite@>=6.2.0 <=6.2.6: '>=6.2.7'
  vite@>=6.2.0 <6.2.5: '>=6.2.5'
  undici@<5.29.0: '>=5.29.0'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
